#!/bin/bash
helpstr='usage: all {problem_id} {solution_source}'
if [[ $1 == '' ]]; then
  echo 'missing problem id'
  echo $helpstr
  exit
fi
if [[ $2 == '' ]]; then
  echo 'missing solution source'
  echo $helpstr
  exit
fi

python "$1_gen.py"
../test_packer.py < groups.spec
../test_runner run $2

